"""
Analysis Action Selector
MODULE:  Analysis Action Selector
Author: Christopher Robson
Copyright by:  Christopher Robson
Copyright date: 08Oct2017
FIXME !! THIS CLASS IS PROPRIETARY AND MAY NOT BE REUSED BY ANYONE BUT THE AUTHOR!!
FIXME THIS MODULE DOES NOT BELONG TO ANY CONTRACTING COMPANY OR THE GOVERNMENT!
FIXME IT WAS DEVELOPED ON THE AUTHORS OWN PERSONAL TIME !!!!!!!!!!!!!!!!!!!!
This software is not FREE!  Use or destribution of the software system and its
subsystem modules, libraries, configuration file and "seed" file without the
express permission of the author is strictly PROHIBITED!
FUNCTION:  This data structure is used to determine what process will be used
          to analysis the collected statistical data. The first value is the
          keyword variable from the KEY:VALUE dictionary of the statistics
          collection logic.  The second field is the action to take.
          Any NOT FOUND keywords is assumed to be a simple compare action.
"""
from DecodeDataProcessor import *
"""
output rate output rate bits per sec
"""
""""""
analyze_actions = \
   [
     # CISCO keywords
     ("input rate time", "pass"),
     ("input rate bits per sec", "pass"),
     ("input rate packets per sec", "pass"),
     ("output rate time", "pass"),
     ("output rate bits per sec", "pass"),
     ("output rate packets per sec", "pass"),
     ("packets/bytes inputs/total drops input ", "pass"),
     ("packets/bytes inputs/total drops input ", "pass"),
     ("packets/bytes inputs/total drops input ", "pass"),
     ("upper-level protocol drops", "pass"),
     ("transition state", "ignore"),
     ("timeout", "pass"),
     ("last input", "pass"),
     ("last output", "pass"),
     ("last clear time", "pass"),
     ("output broadcast packets", ">"),
     ("output multicast packets", ">"),
     ("received broadcast packets", ">"),
     ("received multicast packets", ">"),
     ("input packets", ">"),
     ("input bytes", ">"),
     ("input total drops", "0"),
     ("drops", "0"),
     ("runts", ">"),
     ("giants", ">"),
     ("throttles", ">"),
     ("parity", ">"),
     ("input errors", "<"),
     ("input crc", "<"),
     ("input frame", "<"),
     ("input overrun", "<"),
     ("input ignore", "<"),
     ("input abort", "<"),
     ("output packets", "less than"),
     ("output bytes", "less than"),
     ("output total drops", "0"),
     ("broadcast packets", "less than"),
     ("multicast packets", "less than"),
     ("output errors", "<"),
     ("output underruns", "<"),
     ("output applique", "<"),
     ("output resets", "<"),
     ("failures", "<"),
     ("swapouts", "<"),
     ("transitions", "ignore"),
     # JUNIPER keywords
     ("input bytes", ">"),
     ("input bytes bps", "ignore"),
     ("output bytes", "less than"),
     ("output bytes bps", "ignore"),
     ("input packets", ">"),
     ("input packets pps", "ignore"),
     ("output packets", "less than"),
     ("output packets pps", "ignore"),
     ("transit input bytes", ">"),
     ("transit input bytes bps", "ignore"),
     ("transit output bytes", "less than"),
     ("transit output bytes bps", "ignore"),
     ("transit input packets", ">"),
     ("transit output packets", "less than"),
     ("transit output packets pps", "ignore"),
     ("drop bytes", "<"),
     ("droppackets", "<"),
     ("input errors", "<"),
     ("input drops", "<"),
     ("input framing errors", "<"),
     ("input runts", "<"),
     ("input policed discards", "<"),
     ("input L3 incompletes", "<"),
     ("input L2 channel errors", "<"),
     ("input L2 mismatch timeouts", "<"),
     ("input fifo errors", "<"),
     ("input resource errors", "<"),
     ("output carrier transitions", "ignore"),
     ("output errors", "<"),
     ("output drops", "<"),
     ("output collisions", "<"),
     ("output aged packets", "<"),
     ("output fifo errors", "<"),
     ("output hs link crc errors", "<"),
     ("output mtu errors", "<"),
     ("output resource errors", "<"),
     ("ingress queue counter queued packets", ">"),
     ("ingress queue counter transmitted packets", ">"),
     ("ingress queue counter dropped packets", ">"),
     ("egress queue counter queued packets", ">"),
     ("egress queue counter transmitted packets", ">"),
     ("egress queue counter dropped packets", ">"),
     ("mac total octets received", ">"),
     ("mac total octets transmit", ">"),
     ("mac total  received", ">"),
     ("mac total  transmit", ">"),
     ("mac total octets received", ">"),
     ("mac total octets transmit", ">"),
     ("mac total packets received", ">"),
     ("mac total packets transmit", ">"),
     ("mac unicast packets received", ">"),
     ("mac unicast packets transmit", ">"),
     ("mac broadcast packets received", ">"),
     ("mac broadcast packets transmit", ">"),
     ("mac multicast packets received", ">"),
     ("mac multicast packets transmit", ">"),
     ("mac crc/align errors received", ">"),
     ("mac crc/align errors transmit", ">"),
     ("mac fifo errors received", ">"),
     ("mac fifo errors transmit", ">"),
     ("mac control frames received", ">"),
     ("mac control frames transmit", ">"),
     ("mac pause frames received", ">"),
     ("mac pause frames transmit", ">"),
     ("mac oversized frames received", ">"),
     ("mac oversized frames transmit", ">"),
     ("mac jabber frames received", ">"),
     ("mac jabber frames transmit", ">"),
     ("mac fragment frames received", ">"),
     ("mac fragment frames transmit", ">"),
     ("mac vlan tagged frames received", ">"),
     ("mac vlan tagged frames transmit", ">"),
     ("mac code violations received", ">"),
     ("mac code violations transmit", ">"),
     ("mac otn received overhead bytes", ">"),
     ("filter input packet count received", ">"),
     ("filter input packet count transmit", ">"),
     ("filter input packet reject received", ">"),
     ("filter input packet reject transmit", ">"),
     ("input packet rejects", "ignore"),
     ("input da rejects", "ignore"),
     ("input sa rejects", "ignore"),
     ("filter da reject received", ">"),
     ("filter da reject transmit", ">"),
     ("filter sa reject received", ">"),
     ("filter sa reject transmit", ">"),
     ("filter output packet count", ">"),
     ("filter output packet pad count", ">"),
     ("filter output packet error count", ">"),
     ("filter cam destination filters", ">"),
     ("filter cam source filters", ">"),
     ("mac-validate failures packets", ">"),
     ("mac-validate failures bytes", ">"),
     # Probably should use this ("interface index", "not zero"),
     ("interface index", "pass"),
     # Probably should use this ("snmp ifindex", "not zero"),
     ("snmp ifindex", "pass"),
     ("generation", "pass"),
     ("interface flags internal", "pass"),
     ("transmit sequence number", "pass"),
     ("last received", "pass"),
     ("last sent", "pass"),
     ("last flapped", "pass"),
     ("last cleared", "pass"),
     ("up time", "pass")
   ]
"""
END of FILE
"""
