# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PyQt5InventoryControlGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InventoryControlMainWindow(object):
    def setupUi(self, InventoryControlMainWindow):
        InventoryControlMainWindow.setObjectName("InventoryControlMainWindow")
        InventoryControlMainWindow.resize(1011, 1051)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        InventoryControlMainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(InventoryControlMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DeviceFrame = QtWidgets.QFrame(self.centralwidget)
        self.DeviceFrame.setGeometry(QtCore.QRect(20, 20, 481, 541))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.DeviceFrame.setPalette(palette)
        self.DeviceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeviceFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.DeviceFrame.setLineWidth(10)
        self.DeviceFrame.setObjectName("DeviceFrame")
        self.DeviceID_94 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_94.setGeometry(QtCore.QRect(-40, 60, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_94.setFont(font)
        self.DeviceID_94.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_94.setObjectName("DeviceID_94")
        self.DeviceID_90 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_90.setGeometry(QtCore.QRect(-40, 320, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_90.setFont(font)
        self.DeviceID_90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_90.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_90.setObjectName("DeviceID_90")
        self.DeviceID_84 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_84.setGeometry(QtCore.QRect(-40, 100, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_84.setFont(font)
        self.DeviceID_84.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_84.setObjectName("DeviceID_84")
        self.DeviceID_79 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_79.setGeometry(QtCore.QRect(-40, 180, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_79.setFont(font)
        self.DeviceID_79.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_79.setObjectName("DeviceID_79")
        self.DeviceID_86 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_86.setGeometry(QtCore.QRect(-40, 500, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_86.setFont(font)
        self.DeviceID_86.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_86.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_86.setObjectName("DeviceID_86")
        self.DeviceID_75 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_75.setGeometry(QtCore.QRect(-40, 440, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_75.setFont(font)
        self.DeviceID_75.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_75.setObjectName("DeviceID_75")
        self.DeviceID_80 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_80.setGeometry(QtCore.QRect(-40, 480, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_80.setFont(font)
        self.DeviceID_80.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_80.setObjectName("DeviceID_80")
        self.DeviceID_76 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_76.setGeometry(QtCore.QRect(-40, 340, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_76.setFont(font)
        self.DeviceID_76.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_76.setObjectName("DeviceID_76")
        self.DeviceID_83 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_83.setGeometry(QtCore.QRect(-40, 380, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_83.setFont(font)
        self.DeviceID_83.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_83.setObjectName("DeviceID_83")
        self.DeviceID_74 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_74.setGeometry(QtCore.QRect(-40, 120, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_74.setFont(font)
        self.DeviceID_74.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_74.setObjectName("DeviceID_74")
        self.DeviceID_72 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_72.setGeometry(QtCore.QRect(-40, 220, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_72.setFont(font)
        self.DeviceID_72.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_72.setObjectName("DeviceID_72")
        self.DeviceID_88 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_88.setGeometry(QtCore.QRect(-40, 300, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_88.setFont(font)
        self.DeviceID_88.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_88.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_88.setObjectName("DeviceID_88")
        self.DeviceID_71 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_71.setGeometry(QtCore.QRect(-40, 80, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_71.setFont(font)
        self.DeviceID_71.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_71.setObjectName("DeviceID_71")
        self.DeviceID_77 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_77.setGeometry(QtCore.QRect(-40, 240, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_77.setFont(font)
        self.DeviceID_77.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_77.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_77.setObjectName("DeviceID_77")
        self.DeviceID_78 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_78.setGeometry(QtCore.QRect(-40, 280, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_78.setFont(font)
        self.DeviceID_78.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_78.setObjectName("DeviceID_78")
        self.DeviceID_82 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_82.setGeometry(QtCore.QRect(-40, 360, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_82.setFont(font)
        self.DeviceID_82.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_82.setObjectName("DeviceID_82")
        self.DeviceID_81 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_81.setGeometry(QtCore.QRect(-40, 160, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_81.setFont(font)
        self.DeviceID_81.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_81.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_81.setObjectName("DeviceID_81")
        self.DeviceID_85 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_85.setGeometry(QtCore.QRect(-40, 400, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_85.setFont(font)
        self.DeviceID_85.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_85.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_85.setObjectName("DeviceID_85")
        self.DeviceID_91 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_91.setGeometry(QtCore.QRect(-40, 140, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_91.setFont(font)
        self.DeviceID_91.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_91.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_91.setObjectName("DeviceID_91")
        self.DeviceID_89 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_89.setGeometry(QtCore.QRect(-40, 200, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_89.setFont(font)
        self.DeviceID_89.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_89.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_89.setObjectName("DeviceID_89")
        self.DeviceID_93 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_93.setGeometry(QtCore.QRect(-40, 40, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_93.setFont(font)
        self.DeviceID_93.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_93.setObjectName("DeviceID_93")
        self.DeviceID_87 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_87.setGeometry(QtCore.QRect(-40, 460, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_87.setFont(font)
        self.DeviceID_87.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_87.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_87.setObjectName("DeviceID_87")
        self.DeviceID_73 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_73.setGeometry(QtCore.QRect(-40, 420, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_73.setFont(font)
        self.DeviceID_73.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_73.setObjectName("DeviceID_73")
        self.DeviceID_92 = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceID_92.setGeometry(QtCore.QRect(-40, 260, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_92.setFont(font)
        self.DeviceID_92.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_92.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_92.setObjectName("DeviceID_92")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_24.setGeometry(QtCore.QRect(220, 360, 251, 23))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_22.setGeometry(QtCore.QRect(220, 460, 251, 23))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_7.setGeometry(QtCore.QRect(220, 160, 251, 23))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_17.setGeometry(QtCore.QRect(220, 420, 251, 23))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 40, 251, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_15.setGeometry(QtCore.QRect(220, 240, 251, 23))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_9.setGeometry(QtCore.QRect(220, 260, 251, 23))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 340, 251, 23))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_23.setGeometry(QtCore.QRect(220, 400, 251, 23))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 100, 251, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_20.setGeometry(QtCore.QRect(220, 440, 251, 23))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_12.setGeometry(QtCore.QRect(220, 280, 251, 23))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_19.setGeometry(QtCore.QRect(220, 480, 251, 23))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 80, 251, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_10.setGeometry(QtCore.QRect(220, 220, 251, 23))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_21.setGeometry(QtCore.QRect(220, 500, 251, 23))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 120, 251, 23))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 60, 251, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_16.setGeometry(QtCore.QRect(220, 200, 251, 23))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_18.setGeometry(QtCore.QRect(220, 380, 251, 23))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 180, 251, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 140, 251, 23))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_11.setGeometry(QtCore.QRect(220, 320, 251, 23))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.DeviceFrame)
        self.lineEdit_14.setGeometry(QtCore.QRect(220, 300, 251, 23))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.DeviceLabel = QtWidgets.QLabel(self.DeviceFrame)
        self.DeviceLabel.setGeometry(QtCore.QRect(160, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.DeviceLabel.setFont(font)
        self.DeviceLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DeviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DeviceLabel.setObjectName("DeviceLabel")
        self.DeviceFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.DeviceFrame_2.setGeometry(QtCore.QRect(510, 20, 481, 541))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.DeviceFrame_2.setPalette(palette)
        self.DeviceFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeviceFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.DeviceFrame_2.setLineWidth(10)
        self.DeviceFrame_2.setObjectName("DeviceFrame_2")
        self.DeviceID_95 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_95.setGeometry(QtCore.QRect(-40, 60, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_95.setFont(font)
        self.DeviceID_95.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_95.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_95.setObjectName("DeviceID_95")
        self.DeviceID_96 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_96.setGeometry(QtCore.QRect(-40, 320, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_96.setFont(font)
        self.DeviceID_96.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_96.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_96.setObjectName("DeviceID_96")
        self.DeviceID_97 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_97.setGeometry(QtCore.QRect(-40, 100, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_97.setFont(font)
        self.DeviceID_97.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_97.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_97.setObjectName("DeviceID_97")
        self.DeviceID_98 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_98.setGeometry(QtCore.QRect(-40, 180, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_98.setFont(font)
        self.DeviceID_98.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_98.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_98.setObjectName("DeviceID_98")
        self.DeviceID_99 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_99.setGeometry(QtCore.QRect(-40, 500, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_99.setFont(font)
        self.DeviceID_99.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_99.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_99.setObjectName("DeviceID_99")
        self.DeviceID_100 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_100.setGeometry(QtCore.QRect(-40, 440, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_100.setFont(font)
        self.DeviceID_100.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_100.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_100.setObjectName("DeviceID_100")
        self.DeviceID_101 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_101.setGeometry(QtCore.QRect(-40, 480, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_101.setFont(font)
        self.DeviceID_101.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_101.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_101.setObjectName("DeviceID_101")
        self.DeviceID_102 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_102.setGeometry(QtCore.QRect(-40, 340, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_102.setFont(font)
        self.DeviceID_102.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_102.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_102.setObjectName("DeviceID_102")
        self.DeviceID_103 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_103.setGeometry(QtCore.QRect(-40, 380, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_103.setFont(font)
        self.DeviceID_103.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_103.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_103.setObjectName("DeviceID_103")
        self.DeviceID_104 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_104.setGeometry(QtCore.QRect(-40, 120, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_104.setFont(font)
        self.DeviceID_104.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_104.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_104.setObjectName("DeviceID_104")
        self.DeviceID_105 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_105.setGeometry(QtCore.QRect(-40, 220, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_105.setFont(font)
        self.DeviceID_105.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_105.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_105.setObjectName("DeviceID_105")
        self.DeviceID_106 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_106.setGeometry(QtCore.QRect(-40, 300, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_106.setFont(font)
        self.DeviceID_106.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_106.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_106.setObjectName("DeviceID_106")
        self.DeviceID_107 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_107.setGeometry(QtCore.QRect(-40, 80, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_107.setFont(font)
        self.DeviceID_107.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_107.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_107.setObjectName("DeviceID_107")
        self.DeviceID_108 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_108.setGeometry(QtCore.QRect(-40, 240, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_108.setFont(font)
        self.DeviceID_108.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_108.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_108.setObjectName("DeviceID_108")
        self.DeviceID_109 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_109.setGeometry(QtCore.QRect(-40, 280, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_109.setFont(font)
        self.DeviceID_109.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_109.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_109.setObjectName("DeviceID_109")
        self.DeviceID_110 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_110.setGeometry(QtCore.QRect(-40, 360, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_110.setFont(font)
        self.DeviceID_110.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_110.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_110.setObjectName("DeviceID_110")
        self.DeviceID_111 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_111.setGeometry(QtCore.QRect(-40, 160, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_111.setFont(font)
        self.DeviceID_111.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_111.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_111.setObjectName("DeviceID_111")
        self.DeviceID_112 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_112.setGeometry(QtCore.QRect(-40, 400, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_112.setFont(font)
        self.DeviceID_112.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_112.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_112.setObjectName("DeviceID_112")
        self.DeviceID_113 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_113.setGeometry(QtCore.QRect(-40, 140, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_113.setFont(font)
        self.DeviceID_113.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_113.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_113.setObjectName("DeviceID_113")
        self.DeviceID_114 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_114.setGeometry(QtCore.QRect(-40, 200, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_114.setFont(font)
        self.DeviceID_114.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_114.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_114.setObjectName("DeviceID_114")
        self.DeviceID_115 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_115.setGeometry(QtCore.QRect(-40, 40, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_115.setFont(font)
        self.DeviceID_115.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_115.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_115.setObjectName("DeviceID_115")
        self.DeviceID_116 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_116.setGeometry(QtCore.QRect(-40, 460, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_116.setFont(font)
        self.DeviceID_116.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_116.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_116.setObjectName("DeviceID_116")
        self.DeviceID_117 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_117.setGeometry(QtCore.QRect(-40, 420, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_117.setFont(font)
        self.DeviceID_117.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_117.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_117.setObjectName("DeviceID_117")
        self.DeviceID_118 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceID_118.setGeometry(QtCore.QRect(-40, 260, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceID_118.setFont(font)
        self.DeviceID_118.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DeviceID_118.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DeviceID_118.setObjectName("DeviceID_118")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(220, 360, 251, 23))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(220, 460, 251, 23))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(220, 160, 251, 23))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_28.setGeometry(QtCore.QRect(220, 420, 251, 23))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(220, 40, 251, 23))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_30.setGeometry(QtCore.QRect(220, 240, 251, 23))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(220, 260, 251, 23))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(220, 340, 251, 23))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_33.setGeometry(QtCore.QRect(220, 400, 251, 23))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(220, 100, 251, 23))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(220, 440, 251, 23))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(220, 280, 251, 23))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_37.setGeometry(QtCore.QRect(220, 480, 251, 23))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_38.setGeometry(QtCore.QRect(220, 80, 251, 23))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_39.setGeometry(QtCore.QRect(220, 220, 251, 23))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_40.setGeometry(QtCore.QRect(220, 500, 251, 23))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_41.setGeometry(QtCore.QRect(220, 120, 251, 23))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_42.setGeometry(QtCore.QRect(220, 60, 251, 23))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_43.setGeometry(QtCore.QRect(220, 200, 251, 23))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_44.setGeometry(QtCore.QRect(220, 380, 251, 23))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_45.setGeometry(QtCore.QRect(220, 180, 251, 23))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_46.setGeometry(QtCore.QRect(220, 140, 251, 23))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_47.setGeometry(QtCore.QRect(220, 320, 251, 23))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.DeviceFrame_2)
        self.lineEdit_48.setGeometry(QtCore.QRect(220, 300, 251, 23))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.DeviceLabel_2 = QtWidgets.QLabel(self.DeviceFrame_2)
        self.DeviceLabel_2.setGeometry(QtCore.QRect(160, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.DeviceLabel_2.setFont(font)
        self.DeviceLabel_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DeviceLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DeviceLabel_2.setObjectName("DeviceLabel_2")
        self.InventoryDisplay = QtWidgets.QListWidget(self.centralwidget)
        self.InventoryDisplay.setGeometry(QtCore.QRect(20, 570, 971, 431))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.InventoryDisplay.setPalette(palette)
        self.InventoryDisplay.setLineWidth(10)
        self.InventoryDisplay.setMidLineWidth(5)
        self.InventoryDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InventoryDisplay.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.InventoryDisplay.setObjectName("InventoryDisplay")
        InventoryControlMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InventoryControlMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 20))
        self.menubar.setObjectName("menubar")
        InventoryControlMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InventoryControlMainWindow)
        self.statusbar.setObjectName("statusbar")
        InventoryControlMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InventoryControlMainWindow)
        QtCore.QMetaObject.connectSlotsByName(InventoryControlMainWindow)

    def retranslateUi(self, InventoryControlMainWindow):
        _translate = QtCore.QCoreApplication.translate
        InventoryControlMainWindow.setWindowTitle(_translate("InventoryControlMainWindow", "Inventory Control Window"))
        self.DeviceID_94.setText(_translate("InventoryControlMainWindow", "Serial Number"))
        self.DeviceID_90.setText(_translate("InventoryControlMainWindow", "Building"))
        self.DeviceID_84.setText(_translate("InventoryControlMainWindow", "Vendor"))
        self.DeviceID_79.setText(_translate("InventoryControlMainWindow", "OS Version"))
        self.DeviceID_86.setText(_translate("InventoryControlMainWindow", "Loaner (Yes/No)"))
        self.DeviceID_75.setText(_translate("InventoryControlMainWindow", "Relocated by"))
        self.DeviceID_80.setText(_translate("InventoryControlMainWindow", "ECR"))
        self.DeviceID_76.setText(_translate("InventoryControlMainWindow", "Date Installed"))
        self.DeviceID_83.setText(_translate("InventoryControlMainWindow", "Date Relocated"))
        self.DeviceID_74.setText(_translate("InventoryControlMainWindow", "Type"))
        self.DeviceID_72.setText(_translate("InventoryControlMainWindow", "Module Serial Number"))
        self.DeviceID_88.setText(_translate("InventoryControlMainWindow", "Floor"))
        self.DeviceID_71.setText(_translate("InventoryControlMainWindow", "Site Identifier"))
        self.DeviceID_77.setText(_translate("InventoryControlMainWindow", "Description"))
        self.DeviceID_78.setText(_translate("InventoryControlMainWindow", "Room"))
        self.DeviceID_82.setText(_translate("InventoryControlMainWindow", "Date Removed"))
        self.DeviceID_81.setText(_translate("InventoryControlMainWindow", "Hostname"))
        self.DeviceID_85.setText(_translate("InventoryControlMainWindow", "Installed by"))
        self.DeviceID_91.setText(_translate("InventoryControlMainWindow", "Name"))
        self.DeviceID_89.setText(_translate("InventoryControlMainWindow", "Part Number"))
        self.DeviceID_93.setText(_translate("InventoryControlMainWindow", "Identifier"))
        self.DeviceID_87.setText(_translate("InventoryControlMainWindow", "Project"))
        self.DeviceID_73.setText(_translate("InventoryControlMainWindow", "Removed by"))
        self.DeviceID_92.setText(_translate("InventoryControlMainWindow", "Rack"))
        self.DeviceLabel.setText(_translate("InventoryControlMainWindow", "DEVICE"))
        self.DeviceID_95.setText(_translate("InventoryControlMainWindow", "Serial Number"))
        self.DeviceID_96.setText(_translate("InventoryControlMainWindow", "Building"))
        self.DeviceID_97.setText(_translate("InventoryControlMainWindow", "Vendor"))
        self.DeviceID_98.setText(_translate("InventoryControlMainWindow", "OS Version"))
        self.DeviceID_99.setText(_translate("InventoryControlMainWindow", "Loaner (Yes/No)"))
        self.DeviceID_100.setText(_translate("InventoryControlMainWindow", "Relocated by"))
        self.DeviceID_101.setText(_translate("InventoryControlMainWindow", "ECR"))
        self.DeviceID_102.setText(_translate("InventoryControlMainWindow", "Date Installed"))
        self.DeviceID_103.setText(_translate("InventoryControlMainWindow", "Date Relocated"))
        self.DeviceID_104.setText(_translate("InventoryControlMainWindow", "Type"))
        self.DeviceID_105.setText(_translate("InventoryControlMainWindow", "Device Serial Number"))
        self.DeviceID_106.setText(_translate("InventoryControlMainWindow", "Floor"))
        self.DeviceID_107.setText(_translate("InventoryControlMainWindow", "Site Identifier"))
        self.DeviceID_108.setText(_translate("InventoryControlMainWindow", "Description"))
        self.DeviceID_109.setText(_translate("InventoryControlMainWindow", "Room"))
        self.DeviceID_110.setText(_translate("InventoryControlMainWindow", "Date Removed"))
        self.DeviceID_111.setText(_translate("InventoryControlMainWindow", "Hostname"))
        self.DeviceID_112.setText(_translate("InventoryControlMainWindow", "Installed by"))
        self.DeviceID_113.setText(_translate("InventoryControlMainWindow", "Name"))
        self.DeviceID_114.setText(_translate("InventoryControlMainWindow", "Part Number"))
        self.DeviceID_115.setText(_translate("InventoryControlMainWindow", "Identifier"))
        self.DeviceID_116.setText(_translate("InventoryControlMainWindow", "Project"))
        self.DeviceID_117.setText(_translate("InventoryControlMainWindow", "Removed by"))
        self.DeviceID_118.setText(_translate("InventoryControlMainWindow", "Rack"))
        self.DeviceLabel_2.setText(_translate("InventoryControlMainWindow", "Module"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InventoryControlMainWindow = QtWidgets.QMainWindow()
    ui = Ui_InventoryControlMainWindow()
    ui.setupUi(InventoryControlMainWindow)
    InventoryControlMainWindow.show()
    sys.exit(app.exec_())

